# Практика 0

## Цель работы

1.  Развить практические навыки использования современного стека воспроизводимых исследований
2.  Закрепить знания о современных сетевых протоколах прикладного уровня

## Задание

1.  Подготовить рабочее окружение для работы с Rstudio
2.  Разработать отчет с использованием стека технологий Rmarkdown и Quarto
3.  Оформить отчет в соответствии с шаблоном Методические рекомендации к оформлению отчетов по практическим и лабораторным работам

Этот пример возвращает в строке найденные гласные "a e i o u". Это может оказаться полезным при поиске или обнаружении гласных.

```         
def get_vowels(String):
   return [each for each in String if each in "aeiou"]
get_vowels("animal") # [a, i, a]
get_vowels("sky") # []
get_vowels("football") # [o, o, a]
```

Этот пример используется для превращения каждой первой буквы символов строки в прописную букву. Он работает со строкой из одного или нескольких символов и будет полезен при анализе текста или записи данных в файл и т.п.

```
def capitalize(String):
    return String.title()
capitalize("shop") # [Shop]
capitalize("python programming") # [Python Programming]
capitalize("how are you!") # [How Are You!]
```

## Вывод

В ходе выполненной работы я развила практические навыки использования современного стека воспроизводимых исследований и закрепила знания о современных сетевых протоколах прикладного уровня.